name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build:all

    - name: Test Jest
      run: npm run test:cov

    - name: Test Cy
      run: npm run cy:run:cov

    - name: Cov merge
      run: npm run cov:merge && npm run cov:fin

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./reports/coverage-full-total/

    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage_path: "reports/coverage-full-total/clover.xml"

    - name: Publish
      branches:
        - main
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        msg=$(git log -1 --pretty=%B)
        echo $msg
        
        if [[ "$msg" =~ "[patch]" ]]; then
          echo "publish patch"
          npm run publish:patch
          exit(0)
        fi
        
        if [[ "$msg" =~ "[minor]" ]]; then
          echo "publish minor"
          npm run publish:minor
          exit(0)
        fi
        
        if [[ "$msg" =~ "[major]" ]]; then
          echo "publish major"
          npm run publish:major
          exit(0)
        fi
        
        echo "no publishing, commit message should contain [minor], [major] or [patch]"
        
        
        
